baseURL = 'https://yslasdas.github.io/'
locale = 'en-us'
title = 'Kernel Picnic!'
theme = "hugo-bearblog"

[params]
  author = "Yslasdas"
  description = "Hola amigos de Shutu."
  favicon = "favicon.png"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Things"
    url = "/posts/"
    weight = 2
