baseURL = 'https://yslasdas.github.io/'
locale = 'en-us'
title = 'Filled Void Space'
theme = "hugo-bearblog"

[params]
  author = "Yslasdas"
  description = "Hola amigos de Shutu."

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1